In [101]:
import pandas as pd
import numpy as np

In [102]:
df=pd.read_csv('covid_toy.csv')

In [103]:
df.sample(20)

age  gender  fever   cough       city has_covid
19   42  Female    NaN  Strong  Bangalore       Yes
10   75  Female    NaN    Mild      Delhi        No
36   38  Female  101.0    Mild  Bangalore        No
57   49  Female   99.0  Strong  Bangalore        No
99   10  Female   98.0  Strong    Kolkata       Yes
12   25  Female   99.0  Strong    Kolkata        No
59    6  Female  104.0    Mild    Kolkata       Yes
82   24    Male   98.0    Mild    Kolkata       Yes
23   80  Female   98.0    Mild      Delhi       Yes
34   74    Male  102.0    Mild     Mumbai       Yes
11   65  Female   98.0    Mild     Mumbai       Yes
41   82    Male    NaN    Mild    Kolkata       Yes
71   75  Female  104.0  Strong      Delhi        No
17   40  Female   98.0  Strong      Delhi        No
74   34  Female  104.0  Strong      Delhi        No
37   55    Male  100.0    Mild    Kolkata        No
9    64  Female  101.0    Mild      Delhi        No
93   27    Male  100.0    Mild    Kolkata       Yes
5    84  Female    NaN    Mild  Bangalore       Yes
69   73  Female  103.0    Mild      Delhi        No

In [104]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [105]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [106]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(['has_covid'],axis=1),
                                               df['has_covid'],
                                               test_size=0.2,
                                               random_state=0)

In [107]:
x_train

age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

In [108]:
impute=SimpleImputer()
x_train_fever=impute.fit_transform(x_train[['fever']])

In [109]:
x_test_fever=impute.transform(x_test[['fever']])

In [110]:
x_train_fever

array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [111]:
x_train_fever.shape

(80, 1)

In [112]:
x_train_fever.dtype

dtype('float64')

In [113]:
# ordinal encoder
oe=OrdinalEncoder(categories=[['Mild','Strong']])

In [114]:
x_train_cough=oe.fit_transform(x_train[['cough']])

In [115]:
x_test_cough=oe.transform(x_test[['cough']])

In [116]:
x_train_cough.shape

(80, 1)

In [117]:
# onehotencoder
ohe = OneHotEncoder(drop='first')

x_train_ohe=ohe.fit_transform(x_train[['gender','city']]).toarray()

In [118]:
x_train_ohe.shape

(80, 4)

In [119]:
x_test_ohe=ohe.transform(x_test[['gender','city']])

In [120]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

In [121]:
x_train_age.shape

(80, 1)

In [122]:
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [123]:
X_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_ohe,x_train_cough),axis=1)

In [126]:
x_test_age.shape


(20, 1)

In [127]:
x_test_fever.shape

(20, 1)

In [137]:
x_test_ohe

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [129]:
x_test_cough.shape

(20, 1)

In [130]:
x_test_ohe = ohe.transform(x_test[['gender','city']]).toarray()


In [131]:
X_train_transformed.shape

(80, 7)

In [132]:
X_test_transformed.shape

(20, 7)

In [138]:
X_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_ohe,x_test_cough),axis=1)

In [140]:
X_train_transformed.shape

(80, 7)

In [141]:
X_test_transformed

array([[ 19.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 25.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  5.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 60.        ,  99.        ,   0.        ,   0.        ,
          0.    

In [142]:
X_test_transformed.shape

(20, 7)

In [145]:
x_test_transformed=pd.DataFrame(X_test_transformed)

In [147]:
x_test_transformed

0           1    2    3    4    5    6
0   19.0  100.000000  0.0  0.0  1.0  0.0  0.0
1   25.0  104.000000  1.0  0.0  0.0  0.0  0.0
2   42.0  101.000000  1.0  1.0  0.0  0.0  0.0
3   81.0  101.000000  0.0  0.0  0.0  1.0  0.0
4    5.0  102.000000  1.0  0.0  1.0  0.0  0.0
5   27.0  100.000000  1.0  0.0  1.0  0.0  0.0
6   69.0  103.000000  0.0  0.0  1.0  0.0  0.0
7   34.0   98.000000  1.0  0.0  1.0  0.0  1.0
8   60.0   99.000000  0.0  0.0  0.0  1.0  0.0
9   12.0  104.000000  0.0  0.0  0.0  0.0  0.0
10  83.0   98.000000  1.0  1.0  0.0  0.0  0.0
11  82.0  102.000000  0.0  0.0  1.0  0.0  1.0
12  11.0  100.000000  1.0  0.0  0.0  0.0  0.0
13  64.0  102.000000  1.0  0.0  0.0  0.0  0.0
14  20.0  100.915493  0.0  0.0  0.0  1.0  1.0
15  15.0  101.000000  1.0  1.0  0.0  0.0  0.0
16  71.0   98.000000  0.0  0.0  1.0  0.0  1.0
17  13.0  100.000000  0.0  0.0  1.0  0.0  1.0
18  26.0   98.000000  0.0  0.0  1.0  0.0  0.0
19  19.0  100.000000  0.0  0.0  0.0  0.0  1.0

In [148]:
x_train_transformed=pd.DataFrame(X_train_transformed)

In [149]:
x_train_transformed

0      1    2    3    4    5    6
0   22.0   99.0  0.0  0.0  0.0  0.0  0.0
1   56.0  104.0  0.0  0.0  0.0  0.0  1.0
2   31.0   98.0  0.0  0.0  1.0  0.0  0.0
3   75.0  104.0  0.0  1.0  0.0  0.0  1.0
4   72.0   99.0  1.0  0.0  0.0  0.0  0.0
..   ...    ...  ...  ...  ...  ...  ...
75  51.0  101.0  0.0  0.0  1.0  0.0  1.0
76  65.0   99.0  1.0  0.0  0.0  0.0  0.0
77  42.0  104.0  1.0  0.0  0.0  1.0  0.0
78  18.0  104.0  0.0  0.0  0.0  0.0  0.0
79  20.0  102.0  1.0  1.0  0.0  0.0  1.0

[80 rows x 7 columns]

In [151]:
# mentos zindagi
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')


In [153]:
transformer.fit_transform(x_train).shape

(80, 7)

In [154]:
print(transformer.transform(x_test).shape)


(20, 7)
